# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49df15280974ea7d3ca7945d1178b7177c192e3afb5e903385c92ae2581e12dc5add9884a81d2f804a5168430330ed7e907ad1f6069ae1b882a0343d4da7e236

test:
  secret_key_base: 0117ccca1415ba28451597dd1bfe1e1d5c4961e530773d7438e8a33a8aed98fe4771cb63027f53cbde32aff1bf2ac6fc801018c8b95aebaf88281e16e4e93736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
